name: 🔎 Check Commit

on:
  workflow_dispatch:
  push:
  pull_request:
    types: [opened, synchronize]

jobs:
  check:
    name: 🔎 Run Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: ⚡ Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔎 Lint
        run: yarn lint

      - name: 🔨 Build Library
        run: yarn build:lib
