name: 📖 Documentation

on:
  workflow_dispatch:
  push:
    branches: [master]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: false

jobs:
  release:
    name: 📦☁️ Release
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3
      - uses: actions/configure-pages@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: ⚡ Install dependencies
        run: yarn install --frozen-lockfile

      - name: 🔨 Build documentation
        run: yarn build:docs

      - name: 📡 Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: docs

      - name: ☁️ Publish documentation
        id: deployment
        uses: actions/deploy-pages@v2
